name: HeadZ
version: 1.2.0
main: nl.tabuu.headz.HeadZ
description: The Free Head Database.
author: Tabuu
authors: [Tabuu]
website: https://www.tabuu.nl
depend: [TabuuCore]
api-version: 1.13

commands:
  headz:
    usage: /<command>
    description: Opens the head selector GUI.
    permission: headz.menu
    aliases: [head]

  headz update:
    usage: /<command> <category>
    description: Updates the database
    permission: headz.update

permissions:
  headz.menu:
    description: Allows users to open the head selector.
    default: true
  headz.update:
    description: Allows users to update the database.
    default: op